//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academia.Libraries.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academia.Libraries.Lang.MensagensErro", typeof(MensagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é de preenchimento obrigatório!.
        /// </summary>
        public static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no mínimo {1} caracteres..
        /// </summary>
        public static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no máximo {1} caracteres..
        /// </summary>
        public static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não foi preenchido corretamente..
        /// </summary>
        public static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do campo {0} não confere com o valor do campo {1}..
        /// </summary>
        public static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-Mail informado já foi utilizado anteriormente..
        /// </summary>
        public static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopss.. Houve um erro ao realizar a operação. Tente novamente mais tarde..
        /// </summary>
        public static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais inválidas! Verifique e tente novamente..
        /// </summary>
        public static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado!.
        /// </summary>
        public static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não está cadastrado em nosso sistema. Verifique e tente novamente..
        /// </summary>
        public static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do campo {0} deve estar entre {1} e {2}..
        /// </summary>
        public static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é válido para {1}..
        /// </summary>
        public static string MSG_E012 {
            get {
                return ResourceManager.GetString("MSG_E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi fornecido um valor para o campo {0}..
        /// </summary>
        public static string MSG_E013 {
            get {
                return ResourceManager.GetString("MSG_E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário que o body na requisição não esteja vazio..
        /// </summary>
        public static string MSG_E014 {
            get {
                return ResourceManager.GetString("MSG_E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é válido..
        /// </summary>
        public static string MSG_E015 {
            get {
                return ResourceManager.GetString("MSG_E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor fornecido é inválido..
        /// </summary>
        public static string MSG_E016 {
            get {
                return ResourceManager.GetString("MSG_E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser um número..
        /// </summary>
        public static string MSG_E017 {
            get {
                return ResourceManager.GetString("MSG_E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor fornecido é inválido para {0}..
        /// </summary>
        public static string MSG_E018 {
            get {
                return ResourceManager.GetString("MSG_E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser um número..
        /// </summary>
        public static string MSG_E019 {
            get {
                return ResourceManager.GetString("MSG_E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor nulo é inválido..
        /// </summary>
        public static string MSG_E020 {
            get {
                return ResourceManager.GetString("MSG_E020", resourceCulture);
            }
        }
    }
}
